baseURL = "https://rergfn.github.io/"
title = "Things"
theme = "things"
languageCode = "zh-CN"
hasCJKLanguage = true
disableKinds = ["sitemap", "RSS", "taxonomy", "taxonomyTerm"]

[markup]
[markup.tableOfContents]
endLevel = 5
ordered = false
startLevel = 2
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "dracula"
tabWidth = 4
